// <auto-generated />
namespace projet1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addsize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsize));
        
        string IMigrationMetadata.Id
        {
            get { return "202202051818458_add-size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
